# Auto-labeler configuration for Pull Requests
# Format for actions/labeler@v5

component:agents:
  - changed-files:
      - any-glob-to-any-file: 'src/agents/**/*'

component:core:
  - changed-files:
      - any-glob-to-any-file: 'src/core/**/*'

component:utils:
  - changed-files:
      - any-glob-to-any-file: 'src/utils/**/*'

component:types:
  - changed-files:
      - any-glob-to-any-file: 'src/types/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'

tooling:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**/*'

ci/cd:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.spec.ts'
          - 'tests/**/*'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'tsconfig.json'
          - 'jest.config.js'
          - 'playwright.config.ts'

dependencies:
  - changed-files:
      - any-glob-to-any-file: 'package.json'

code-quality:
  - changed-files:
      - any-glob-to-any-file:
          - '.eslintrc*'
          - '.prettierrc*'
          - '.editorconfig'
