'use client';

import { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';

const MOCK_PREVIEW = `// Generated Component
export default function Card({ title }) {
  return (
    <div className="p-6 bg-white rounded-xl shadow-lg">
      <h2 className="text-xl font-bold mb-2">{title}</h2>
      <p className="text-gray-600">Generated by PrismCode Visual Engine</p>
    </div>
  )
}`;

export default function VisualPreviewPage() {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedCode, setGeneratedCode] = useState('');
  const [view, setView] = useState<'preview' | 'code'>('preview');

  const handleGenerate = () => {
    if (!prompt) return;
    setIsGenerating(true);
    // Simulate generation delay
    setTimeout(() => {
      setIsGenerating(false);
      setGeneratedCode(MOCK_PREVIEW);
    }, 1500);
  };

  return (
    <div className="h-[calc(100vh-4rem)] flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-violet-600 to-purple-600 bg-clip-text text-transparent">
            Visual Preview
          </h1>
          <p className="text-muted-foreground mt-1">Text-to-UI generation engine</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm">
            History
          </Button>
          <Button variant="outline" size="sm">
            Export
          </Button>
        </div>
      </div>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-6 min-h-0">
        {/* Left Panel: Input & Settings */}
        <div className="flex flex-col gap-4 h-full">
          <Card className="flex-1 p-4 flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <span className="font-medium text-sm">Prompt</span>
              <Badge variant="outline">gpt-4o</Badge>
            </div>
            <Textarea
              placeholder="Describe your UI component... (e.g., 'A responsive pricing card with 3 tiers')"
              className="flex-1 min-h-[150px] resize-none font-mono text-sm leading-relaxed"
              value={prompt}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setPrompt(e.target.value)}
            />
            <div className="flex items-center justify-between">
              <div className="flex gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setPrompt('Login form with social auth')}
                >
                  Example 1
                </Button>
                <Button variant="ghost" size="sm" onClick={() => setPrompt('Dashboard stats grid')}>
                  Example 2
                </Button>
              </div>
              <Button
                onClick={handleGenerate}
                disabled={isGenerating || !prompt}
                className="bg-gradient-to-r from-violet-600 to-purple-600 text-white min-w-[120px]"
              >
                {isGenerating ? 'Generating...' : 'Generate UI'}
              </Button>
            </div>
          </Card>

          <Card className="h-1/3 p-4">
            <div className="flex items-center justify-between mb-2">
              <span className="font-medium text-sm">Generated Code</span>
              <div className="flex gap-2">
                <Button variant="ghost" size="icon" className="h-6 w-6">
                  📋
                </Button>
              </div>
            </div>
            <pre className="text-xs font-mono text-muted-foreground overflow-auto h-[calc(100%-2rem)] p-2 bg-muted/50 rounded">
              {generatedCode || '// Code will appear here...'}
            </pre>
          </Card>
        </div>

        {/* Right Panel: Preview */}
        <Card className="h-full flex flex-col overflow-hidden bg-zinc-100 dark:bg-zinc-900 border-2 border-dashed">
          <div className="p-2 border-b bg-background/50 backdrop-blur flex items-center justify-between">
            <div className="flex gap-1 bg-muted p-1 rounded-lg">
              <button
                onClick={() => setView('preview')}
                className={`px-3 py-1 text-xs rounded-md transition-colors ${view === 'preview' ? 'bg-background shadow-sm' : 'hover:bg-background/50'}`}
              >
                Preview
              </button>
              <button
                onClick={() => setView('code')}
                className={`px-3 py-1 text-xs rounded-md transition-colors ${view === 'code' ? 'bg-background shadow-sm' : 'hover:bg-background/50'}`}
              >
                Code
              </button>
            </div>
            <div className="flex gap-2">
              <div className="h-2 w-2 rounded-full bg-red-400" />
              <div className="h-2 w-2 rounded-full bg-yellow-400" />
              <div className="h-2 w-2 rounded-full bg-green-400" />
            </div>
          </div>

          <div className="flex-1 flex items-center justify-center p-8 overflow-auto">
            {isGenerating ? (
              <div className="flex flex-col items-center gap-4 animate-pulse">
                <div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                <p className="text-sm text-muted-foreground">Dreaming up your UI...</p>
              </div>
            ) : generatedCode ? (
              <div className="bg-white dark:bg-zinc-950 shadow-2xl rounded-xl p-8 max-w-md w-full border">
                {/* Mock Rendered Component */}
                <h2 className="text-xl font-bold mb-4">Generated Example</h2>
                <div className="space-y-4">
                  <div className="h-4 bg-muted rounded w-3/4" />
                  <div className="h-4 bg-muted rounded w-1/2" />
                  <div className="h-10 bg-primary/10 rounded w-full mt-4" />
                </div>
              </div>
            ) : (
              <div className="text-center text-muted-foreground">
                <div className="text-4xl mb-4 opacity-20">🎨</div>
                <p>Enter a prompt to generate UI</p>
              </div>
            )}
          </div>
        </Card>
      </div>
    </div>
  );
}
